name: Fetch ETFs Data

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup directory and fetch data
        run: |
          mkdir -p data
          echo "Creating ETF data file..."
          echo "{" > data/etfs.json
          echo "  \"last_updated\": \"$(date -u)\"," >> data/etfs.json
          echo "  \"data\": " >> data/etfs.json
          curl -L 'https://script.google.com/macros/s/AKfycbztCTioDVzT8QTzkq7HIQzMBQfHJ9mrXK_hdoXg94bF8rPU0IhYhMnCqKRS9rusGOE9/exec' | jq '.' >> data/etfs.json

          echo "File contents:"
          cat data/etfs.json

          echo "Directory structure:"
          ls -R data/

      - name: Commit and push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/etfs.json
          git commit -m "Update ETF data [skip ci]" || echo "No changes to commit"
          git push